Repository vesoft-inc/nebula-storage, pull requests merged in 2020-10, with the labels that each got.

#159 add new expresions
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#112 improve errorcode
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#154 Fixed rebuild index bug
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildEdgeIndexTask.h
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildIndexTask.h
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.h
  src/storage/test/RebuildIndexTest.cpp
  src/utils/IndexKeyUtils.cpp
  src/utils/IndexKeyUtils.h
Labels: Ready-to-review, bug, ready-for-testing

#167 correct wal_ttl value
  conf/nebula-storaged.conf.default
Labels: Ready-to-review, ready-for-testing

#160 Don't return the not exist key as row.
  src/storage/exec/GetPropNode.h
  src/storage/query/GetPropProcessor.cpp
  src/storage/test/GetPropTest.cpp
Labels: ready-for-testing

#163 Update db dump's name
  src/tools/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-dump/DbDumpTool.cpp
  src/tools/db-dump/DbDumper.cpp
  src/tools/db-dump/DbDumper.h
Labels: Ready-to-review, ready-for-testing

#153 Support read/write time to storage
  src/codec/RowReaderV2.cpp
  src/codec/RowWriterV2.cpp
  src/codec/RowWriterV2.h
  src/codec/test/RowReaderV2Test.cpp
  src/codec/test/RowWriterV2Test.cpp
  src/codec/test/SchemaWriter.cpp
Labels: ready-for-testing

#171 Normalize suffix for index scan
  src/storage/exec/IndexOutputNode.h
  src/storage/test/LookupIndexTest.cpp
Labels: Ready-to-review, ready-for-testing

#131 Support to save default value to expression
  src/codec/RowWriterV2.cpp
  src/codec/test/CMakeLists.txt
  src/codec/test/ResultSchemaProvider.cpp
  src/codec/test/ResultSchemaProvider.h
  src/codec/test/RowWriterV2Test.cpp
  src/codec/test/SchemaWriter.cpp
  src/codec/test/SchemaWriter.h
  src/kvstore/test/CMakeLists.txt
  src/meta/processors/schemaMan/SchemaUtil.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/mock/MockData.cpp
  src/storage/context/StorageExpressionContext.cpp
  src/storage/exec/QueryUtils.h
  src/storage/exec/UpdateNode.h
  src/storage/test/CMakeLists.txt
  src/utils/DefaultValueContext.h
Labels: ready-for-testing

#177 Fix container expression items getter function
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#162 update keywords
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#172 Fix storage would return wrong int vid ending with '\0'
  src/kvstore/raftex/test/RaftexTestBase.cpp
  src/kvstore/raftex/test/RaftexTestBase.h
  src/mock/AdHocSchemaManager.cpp
  src/mock/AdHocSchemaManager.h
  src/mock/MockCluster.h
  src/storage/BaseProcessor.h
  src/storage/CommonUtils.h
  src/storage/context/StorageExpressionContext.cpp
  src/storage/context/StorageExpressionContext.h
  src/storage/exec/AggregateNode.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/exec/GetPropNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/RelNode.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/QueryBaseProcessor.inl
  src/storage/test/GetNeighborsBenchmark.cpp
  src/storage/test/GetNeighborsTest.cpp
  src/storage/test/ScanEdgePropBenchmark.cpp
Labels: Ready-to-review, ready-for-testing

#178 Add time_utils obj.
  src/codec/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/edges-dump/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: Ready-to-review, ready-for-testing

#176 Fix index id not setting when create with not exist flag
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
Labels: ready-for-testing

#179 Fix admin service address
  src/meta/processors/jobMan/MetaJobExecutor.cpp
Labels: Ready-to-review, ready-for-testing

#169 Support more callback in event listener
  src/kvstore/EventListner.h
Labels: Ready-to-review, ready-for-testing

#184 Specify nebula common branch when packaging
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
  package/package.sh
Labels: ready-for-testing

#150 Support scan in storage
  src/storage/CMakeLists.txt
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/GraphStorageServiceHandler.h
  src/storage/admin/AdminTask.h
  src/storage/exec/QueryUtils.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/query/ScanVertexProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/GetNeighborsTest.cpp
  src/storage/test/QueryTestUtils.h
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
Labels: Ready-to-review, ready-for-testing

#185 support listener for meta
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/Common.h
  src/meta/processors/listenerMan/ListenerProcessor.cpp
  src/meta/processors/listenerMan/ListenerProcessor.h
  src/meta/processors/partsMan/DropSpaceProcessor.cpp
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing

#187 Fix admin server host
  src/meta/processors/admin/AdminClient.cpp
  src/meta/test/AdminClientTest.cpp
Labels: ready-for-testing
