Repository vesoft-inc/nebula-storage, pull requests merged in 2020-12, with the labels that each got.

#227 print NEBULA_COMMON_REPO_TAG
  cmake/FetchModule.cmake
Labels: Ready-to-review, ready-for-testing

#225 dedup show index status result
  src/meta/processors/jobMan/ListEdgeIndexStatusProcessor.cpp
  src/meta/processors/jobMan/ListTagIndexStatusProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#199 Balance for zone
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/CMakeLists.txt
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/Common.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/BalanceProcessor.h
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/GetStatisTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/storage/admin/AdminProcessor.h
Labels: ready-for-testing

#223 Show host graph
  src/kvstore/NebulaStore.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/test/GroupZoneTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/utils/Utils.h
Labels: Ready-to-review, ready-for-testing

#109 Toss
  src/codec/RowWriterV2.h
  src/daemons/CMakeLists.txt
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/plugins/hbase/HBaseStore.h
  src/meta/test/CMakeLists.txt
  src/storage/CMakeLists.txt
  src/storage/CommonUtils.cpp
  src/storage/CommonUtils.h
  src/storage/CompactionFilter.h
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/GraphStorageServiceHandler.h
  src/storage/InternalStorageServiceHandler.cpp
  src/storage/InternalStorageServiceHandler.h
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/exec/EdgeNode.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesAtomicProcessor.cpp
  src/storage/mutate/AddEdgesAtomicProcessor.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/test/AdminTaskManagerTest.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/TossBenchmark.cpp
  src/storage/test/TossEnvironment.h
  src/storage/test/TossErrorTest.cpp
  src/storage/test/TossHappyTest.cpp
  src/storage/transaction/GetValueProcessor.cpp
  src/storage/transaction/GetValueProcessor.h
  src/storage/transaction/TossEdgeIterator.h
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
  src/storage/transaction/TransactionProcessor.cpp
  src/storage/transaction/TransactionProcessor.h
  src/storage/transaction/TransactionTypes.h
  src/storage/transaction/TransactionUtils.cpp
  src/storage/transaction/TransactionUtils.h
  src/tools/db-dump/CMakeLists.txt
  src/tools/edges-dump/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
  src/utils/NebulaKeyUtils.cpp
  src/utils/NebulaKeyUtils.h
  src/utils/Utils.h
Labels: depend on common, ready-for-testing

#233 revert respGen AdminClient::addTask
  src/meta/processors/admin/AdminClient.cpp
Labels: Ready-to-review, ready-for-testing

#229 add listener config file and change default ip
  conf/nebula-metad.conf.production
  conf/nebula-storaged-listener.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
Labels: Ready-to-review, ready-for-testing

#237 change docker image tags
  .github/workflows/docker.yml
Labels: ready-for-testing

#224 Unify all storage interface behavior
  src/codec/RowReaderWrapper.cpp
  src/storage/context/StorageExpressionContext.cpp
  src/storage/exec/EdgeNode.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/exec/GetPropNode.h
  src/storage/exec/HashJoinNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/RelNode.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/TagNode.h
  src/storage/exec/UpdateNode.h
  src/storage/exec/UpdateResultNode.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/index/LookupProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/GetPropProcessor.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/query/ScanVertexProcessor.h
  src/storage/test/GetNeighborsTest.cpp
  src/storage/test/GetPropTest.cpp
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/QueryTestUtils.h
  src/storage/test/ScanEdgePropBenchmark.cpp
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
  src/storage/test/UpdateEdgeTest.cpp
  src/storage/test/UpdateVertexTest.cpp
Labels: Ready-to-review, depend on common, ready-for-testing

#239 Choose default port numbers to reduce chances of conflicts
  conf/nebula-metad.conf.default
  conf/nebula-metad.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/meta/test/MetaHttpDownloadHandlerTest.cpp
  src/meta/test/MetaHttpIngestHandlerTest.cpp
  src/storage/test/StorageHttpAdminHandlerTest.cpp
  src/storage/test/StorageHttpDownloadHandlerTest.cpp
  src/storage/test/StorageHttpIngestHandlerTest.cpp
  src/storage/test/StorageHttpStatsHandlerTest.cpp
Labels: ready-for-testing

#222 enable and add more UT
  src/mock/AdHocIndexManager.cpp
  src/mock/AdHocIndexManager.h
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/storage/CompactionFilter.h
  src/storage/test/CMakeLists.txt
  src/storage/test/CompactionTest.cpp
  src/storage/test/QueryTestUtils.h
  src/storage/test/StorageHttpAdminHandlerTest.cpp
  src/storage/test/StorageHttpDownloadHandlerTest.cpp
  src/storage/test/StorageHttpIngestHandlerTest.cpp
Labels: Ready-to-review, ready-for-testing

#240 Fix rebuild unable to exit
  src/storage/exec/UpdateNode.h
Labels: Ready-to-review, ready-for-testing

#243 bug fix: shutdown storage server may core, if internal storage thread is not stopped. & some toss bug fix
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/test/TossEnvironment.h
  src/storage/test/TossHappyTest.cpp
  src/storage/test/TossTestUtils.h
  src/storage/transaction/GetValueProcessor.cpp
  src/storage/transaction/TossEdgeIterator.h
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
  src/storage/transaction/TransactionProcessor.cpp
  src/storage/transaction/TransactionTypes.h
  src/tools/edges-dump/EdgesDumpTool.cpp
Labels: Ready-to-review, ready-for-testing

#245 fix fetch prop on tag not get the correct result
  src/storage/exec/GetPropNode.h
Labels: Ready-to-review, ready-for-testing

#248 Fixed index rebuilding task
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
Labels: ready-for-testing

#249 let admin task manger catch exception of tasks
  src/storage/admin/AdminTaskManager.cpp
Labels: ready-for-testing

#242 rewrite vertex cache UT
  src/storage/test/CMakeLists.txt
  src/storage/test/GetPropTest.cpp
  src/storage/test/TestUtils.h
  src/storage/test/VertexCacheTest.cpp
Labels: Ready-to-review, ready-for-testing

#255 Remove the bind of meta client of interface of manager.
  src/mock/AdHocIndexManager.h
  src/mock/MockCluster.cpp
  src/storage/StorageServer.cpp
  src/storage/test/TossEnvironment.h
Labels: ready-for-testing

#241 fix crash in AtomicLogBuffer
  src/kvstore/wal/AtomicLogBuffer.h
  src/kvstore/wal/CMakeLists.txt
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/WalFileInfo.h
  src/kvstore/wal/test/AtomicLogBufferTest.cpp
  src/kvstore/wal/test/CMakeLists.txt
  src/kvstore/wal/test/InMemoryLogBuffer.cpp
  src/kvstore/wal/test/InMemoryLogBuffer.h
  src/kvstore/wal/test/InMemoryLogBufferList.h
  src/kvstore/wal/test/InMemoryLogBufferTest.cpp
  src/kvstore/wal/test/LogBufferBenchmark.cpp
Labels: Ready-to-review, ready-for-testing

#258 fix submit job not need spacename
  src/meta/processors/jobMan/AdminJobProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#246 fix integer vId
  src/meta/KVBasedClusterIdMan.h
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/GraphStorageServiceHandler.h
  src/storage/StorageServer.cpp
  src/storage/exec/GetNeighborsNode.h
  src/storage/exec/GetPropNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/QueryUtils.h
  src/storage/query/GetUUIDProcessor.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/VertexCacheTest.cpp
Labels: Ready-to-review, ready-for-testing

#260 Fix fetch problem
  src/storage/exec/GetPropNode.h
  src/storage/test/VertexCacheTest.cpp
Labels: Ready-to-review, ready-for-testing

#252 bug fix: update may crash if use toss.
  src/storage/exec/UpdateNode.h
  src/storage/test/TossEnvironment.h
  src/storage/test/TossHappyTest.cpp
  src/storage/transaction/TossEdgeIterator.h
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
  src/storage/transaction/TransactionUtils.cpp
  src/storage/transaction/TransactionUtils.h
Labels: ready-for-testing

#232 Replace injector with gmock, support clean invalid balance plan
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/processors/jobMan/JobDescription.h
  src/meta/processors/jobMan/JobManager.h
  src/meta/test/BalancerTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/GetStatisTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/meta/test/MockAdminClient.h
  src/meta/test/TestUtils.h
Labels: Ready-to-review, depend on common, ready-for-testing

#261 fix storage server stop, fix meta client related ut would hang
  src/meta/test/MetaClientTest.cpp
  src/meta/test/MockAdminClient.h
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/test/KVClientTest.cpp
  src/storage/test/StorageClientTest.cpp
Labels: Ready-to-review, ready-for-testing

#262 Initialize the timezone information in metad.
  src/daemons/MetaDaemon.cpp
Labels: ready-for-testing

#259 remove ENABLE_NATIVE
  CMakeLists.txt
  src/tools/CMakeLists.txt
Labels: Ready-to-review, ready-for-testing

#263 fix integer lower/upper bound
  src/codec/RowWriterV2.cpp
  src/codec/test/RowWriterV2Test.cpp
Labels: Ready-to-review, ready-for-testing

#265 set storage version at the beginning of storage daemon
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#266 Fix the integer vid type error.
  src/storage/context/StorageExpressionContext.cpp
Labels: bug, ready-for-testing

#267 fix show index status "not exist" bug
  src/meta/processors/jobMan/ListEdgeIndexStatusProcessor.cpp
  src/meta/processors/jobMan/ListTagIndexStatusProcessor.cpp
Labels: bug, ready-for-testing

#264 Support stop current running job in job manager.
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/processors/jobMan/MetaJobExecutor.cpp
  src/meta/processors/jobMan/MetaJobExecutor.h
Labels: ready-for-testing

#256 Added validity check for timestamp default value and more test
  src/codec/RowWriterV2.cpp
  src/codec/test/CMakeLists.txt
  src/codec/test/RowWriterV2Test.cpp
  src/daemons/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/processors/schemaMan/SchemaUtil.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/MetaClientTest.cpp
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/edges-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#269 fix admin client leader change and bug in transfer leader
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/test/AdminClientTest.cpp
  src/storage/admin/AdminProcessor.h
Labels: Ready-to-review, ready-for-testing

#272 Add type check for alter schema
  src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing

#271 add some toss test case
  src/storage/test/CMakeLists.txt
  src/storage/test/TossEnvironment.h
  src/storage/test/TossErrorTest.cpp
  src/storage/test/TossHappyTest.cpp
  src/storage/test/TossTest.cpp
Labels: Ready-to-review, ready-for-testing

#275 Simplify rebuild index count, storage support rebuild multi index
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/CommonUtils.h
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildEdgeIndexTask.h
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildIndexTask.h
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/transaction/TransactionManager.cpp
Labels: Ready-to-review, ready-for-testing

#276 Fix alter fixed_string
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
Labels: ready-for-testing

#278 Fix getPartsNum in AdHocSchemaManager
  src/mock/AdHocSchemaManager.h
Labels: Ready-to-review, ready-for-testing

#279 if genSubTask return empty, task manager won't report task finish
  src/mock/AdHocSchemaManager.h
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/RebuildIndexTask.cpp
Labels: Ready-to-review, ready-for-testing

#280 fix a UT caused heap-use-after-free problem of job manager
  src/meta/test/JobManagerTest.cpp
Labels: Ready-to-review, ready-for-testing

#273 Fix version issue of storage and meta binary
  .github/workflows/pull_request.yml
  .gitignore
  CMakeLists.txt
  src/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/GetStatisTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/storage/StorageServer.cpp
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/edges-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
  src/version/CMakeLists.txt
  src/version/Version.cpp.in
  src/version/Version.h
Labels: ready-for-testing
