Repository vesoft-inc/nebula-storage, pull requests merged in 2020-11, with the labels that each got.

#182 Initialize the timezone configuration.
  src/daemons/StorageDaemon.cpp
Labels: ready-for-testing

#189 cherry-pick from 1.0 for checkpoint
  src/kvstore/NebulaStore.cpp
  src/kvstore/RocksEngine.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/listenerMan/ListenerProcessor.cpp
Labels: ready-for-testing

#174 support get all vertices on tag, get all edges on edgetype
  src/meta/MetaServiceUtils.cpp
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
  src/meta/test/ProcessorTest.cpp
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/mock/MockData.cpp
  src/mock/MockData.h
  src/storage/exec/IndexOutputNode.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/QueryTestUtils.h
  src/storage/test/RebuildIndexTest.cpp
Labels: Ready-to-review, doc required, ready-for-testing

#183 Support case expr
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#158 Support string type index to add | delete | update | scan
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/mock/MockData.cpp
  src/mock/MockData.h
  src/storage/context/StorageExpressionContext.cpp
  src/storage/context/StorageExpressionContext.h
  src/storage/exec/IndexFilterNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/IndexScanNode.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/test/IndexWriteTest.cpp
  src/storage/test/QueryTestUtils.h
  src/utils/IndexKeyUtils.cpp
  src/utils/IndexKeyUtils.h
  src/utils/test/IndexKeyUtilsTest.cpp
Labels: Ready-to-review, doc required, ready-for-testing

#194 NebulaStore can read from follower
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/HBaseStore.h
Labels: Ready-to-review, ready-for-testing

#188 Support space level statistics
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/jobMan/GetStatisProcessor.cpp
  src/meta/processors/jobMan/GetStatisProcessor.h
  src/meta/processors/jobMan/JobDescription.cpp
  src/meta/processors/jobMan/JobDescription.h
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/processors/jobMan/JobStatus.cpp
  src/meta/processors/jobMan/MetaJobExecutor.cpp
  src/meta/processors/jobMan/MetaJobExecutor.h
  src/meta/processors/jobMan/RebuildEdgeJobExecutor.h
  src/meta/processors/jobMan/RebuildJobExecutor.cpp
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/meta/processors/jobMan/StatisJobExecutor.h
  src/meta/processors/partsMan/DropSpaceProcessor.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/GetStatisTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/storage/CMakeLists.txt
  src/storage/admin/AdminTask.cpp
  src/storage/admin/AdminTask.h
  src/storage/admin/AdminTaskManager.cpp
  src/storage/admin/AdminTaskProcessor.cpp
  src/storage/admin/AdminTaskProcessor.h
  src/storage/admin/StatisTask.cpp
  src/storage/admin/StatisTask.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/test/AdminTaskManagerTest.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/StatisTaskTest.cpp
Labels: Ready-to-review, ready-for-testing

#196 Flatten LogicalExpression
  src/storage/index/LookupBaseProcessor.inl
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#200 Fix crash for string property index which has been created before new index syntax
  src/storage/exec/IndexScanNode.h
Labels: ready-for-testing

#186 Support create space with zone (#181)
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.h
  src/meta/processors/partsMan/GetPartsAllocProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/zoneMan/AddZoneProcessor.cpp
  src/meta/processors/zoneMan/DropGroupProcessor.cpp
  src/meta/processors/zoneMan/UpdateGroupProcessor.cpp
  src/meta/processors/zoneMan/UpdateZoneProcessor.cpp
  src/meta/test/GroupZoneTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: Ready-to-review, ready-for-testing

#198 Submit job statis && show status
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/meta/processors/jobMan/StatisJobExecutor.h
  src/meta/test/GetStatisTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/storage/admin/StatisTask.cpp
  src/storage/admin/StatisTask.h
  src/storage/test/StatisTaskTest.cpp
Labels: Ready-to-review, ready-for-testing

#202 fix job manager may remove queue jobs
  src/meta/processors/jobMan/JobManager.cpp
Labels: Ready-to-review, ready-for-testing

#201 Add the lack handling of time type.
  src/codec/RowWriterV2.cpp
  src/meta/processors/schemaMan/SchemaUtil.cpp
Labels: ready-for-testing

#204 encode null as 0xFF instead of \0, support lookup filter out of index
  src/storage/exec/HashJoinNode.h
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexFilterNode.h
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/test/LookupIndexTest.cpp
  src/utils/IndexKeyUtils.h
Labels: Ready-to-review, ready-for-testing

#203 Fix balance failed
  src/codec/RowWriterV2.cpp
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/test/AdminClientTest.cpp
  src/meta/test/BalancerTest.cpp
Labels: ready-for-testing

#207 Fix multi thread error
  src/codec/RowWriterV2.cpp
  src/storage/context/StorageExpressionContext.cpp
  src/storage/exec/QueryUtils.h
  src/storage/exec/UpdateNode.h
Labels: ready-for-testing

#205 Add check wrong null type
  src/meta/processors/schemaMan/SchemaUtil.cpp
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing

#206 fix: task manager should continue not exit if some task gen sub taks …
  src/storage/admin/AdminTaskManager.cpp
  src/storage/test/AdminTaskManagerTest.cpp
Labels: ready-for-testing

#212 fix FlushTask not return correct error code
  src/kvstore/Common.h
  src/meta/processors/jobMan/JobDescription.cpp
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/meta/test/GetStatisTest.cpp
  src/storage/admin/FlushTask.cpp
  src/storage/test/KVTest.cpp
Labels: ready-for-testing

#195 Feature/tune new interface
  src/codec/RowWriterV2.cpp
  src/storage/context/StorageExpressionContext.cpp
  src/storage/exec/FilterNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/QueryUtils.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/utils/IndexKeyUtils.h
Labels: ready-for-testing

#210 Job deduplication and priority
  src/meta/processors/jobMan/AdminJobProcessor.cpp
  src/meta/processors/jobMan/JobDescription.h
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/test/JobManagerTest.cpp
Labels: Ready-to-review, ready-for-testing

#213 Enable the timestamp value from string.
  src/meta/processors/schemaMan/SchemaUtil.cpp
Labels: ready-for-testing

#208 Encode string null in index as length in schema
  src/mock/MockData.cpp
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/exec/IndexScanNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/test/IndexWriteTest.cpp
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/QueryTestUtils.h
  src/utils/IndexKeyUtils.cpp
  src/utils/IndexKeyUtils.h
  src/utils/test/IndexKeyUtilsTest.cpp
Labels: Ready-to-review, ready-for-testing

#180 Listener interface
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/daemons/StorageDaemon.cpp
  src/kvstore/CMakeLists.txt
  src/kvstore/EventListner.h
  src/kvstore/KVStore.h
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/ListenerFactory.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.h
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/kvstore/plugins/CMakeLists.txt
  src/kvstore/plugins/elasticsearch/ESListener.h
  src/kvstore/plugins/hbase/test/HBaseStoreTest.cpp
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/test/CMakeLists.txt
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/Wal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
  src/meta/processors/listenerMan/ListenerProcessor.cpp
  src/meta/test/MetaClientTest.cpp
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
Labels: Ready-to-review, ready-for-testing

#218 fix memory leak
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/test/NebulaListenerTest.cpp
Labels: ready-for-testing

#209 A little optimization for insert vertice/edges and rebuild index
  src/meta/test/JobManagerTest.cpp
  src/storage/CommonUtils.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#197 Integrate listener and fulltext adapter.
  src/daemons/CMakeLists.txt
  src/kvstore/CMakeLists.txt
  src/kvstore/Listener.cpp
  src/kvstore/plugins/elasticsearch/ESListener.cpp
  src/kvstore/plugins/elasticsearch/ESListener.h
  src/kvstore/test/CMakeLists.txt
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/Common.h
  src/meta/processors/indexMan/FTServiceProcessor.cpp
  src/meta/processors/indexMan/FTServiceProcessor.h
  src/meta/test/CMakeLists.txt
  src/meta/test/MetaClientTest.cpp
  src/mock/AdHocSchemaManager.cpp
  src/mock/AdHocSchemaManager.h
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/storage/test/CMakeLists.txt
  src/storage/test/ElasticSearchBulkInsertTest.cpp
  src/tools/db-dump/CMakeLists.txt
  src/tools/edges-dump/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: Ready-to-review, ready-for-testing

#216 add getcolumn for context
  src/storage/context/StorageExpressionContext.h
  src/utils/DefaultValueContext.h
Labels: ready-for-testing

#219 Modify statis to stats
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/MetaJobExecutor.cpp
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/meta/test/GetStatisTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/storage/admin/AdminTask.cpp
  src/storage/test/StatisTaskTest.cpp
Labels: ready-for-testing

#192 show tag/edge index status
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/processors/indexMan/ListEdgeIndexStatusProcessor.cpp
  src/meta/processors/indexMan/ListTagIndexStatusProcessor.cpp
  src/meta/processors/jobMan/ListEdgeIndexStatusProcessor.cpp
  src/meta/processors/jobMan/ListEdgeIndexStatusProcessor.h
  src/meta/processors/jobMan/ListTagIndexStatusProcessor.cpp
  src/meta/processors/jobMan/ListTagIndexStatusProcessor.h
  src/meta/processors/jobMan/RebuildJobExecutor.cpp
  src/meta/test/JobManagerTest.cpp
Labels: ready-for-testing

#221 Support regular expression
  src/storage/query/QueryBaseProcessor.inl
Labels: Ready-to-review, ready-for-testing

#220 modify scan interface, unify fetch colname
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/GetPropTest.cpp
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/QueryTestUtils.h
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
Labels: Ready-to-review, ready-for-testing
