Repository vesoft-inc/nebula-storage, pull requests merged in 2021-06, with the labels that each got.

#474 update EventListner
  src/kvstore/EventListner.h
Labels: ready-for-testing

#477 add null empty
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#476 Fix comments
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/Listener.h
Labels: ready-for-testing

#377 Distinguish between system space and user-created space during backup
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/test/FileBasedWalTest.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/CreateBackupProcessor.cpp
  src/meta/processors/admin/CreateBackupProcessor.h
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/CreateSnapshotProcessor.h
  src/meta/processors/admin/GetMetaDirInfoProcessor.cpp
  src/meta/processors/admin/GetMetaDirInfoProcessor.h
  src/meta/processors/admin/ListClusterInfoProcessor.cpp
  src/meta/processors/admin/ListClusterInfoProcessor.h
  src/meta/processors/admin/SnapShot.cpp
  src/meta/processors/admin/SnapShot.h
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/test/AdminClientTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/CreateBackupProcessorTest.cpp
  src/meta/test/ListClusterInfoTest.cpp
  src/meta/test/MockAdminClient.h
  src/meta/test/RestoreProcessorTest.cpp
  src/storage/CMakeLists.txt
  src/storage/StorageAdminServiceHandler.cpp
  src/storage/StorageAdminServiceHandler.h
  src/storage/admin/CreateCheckpointProcessor.cpp
  src/storage/admin/ListClusterInfoProcessor.cpp
  src/storage/admin/ListClusterInfoProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/ListClusterInfoTest.cpp
Labels: depend on common, doc affected, ready-for-testing

#475 Set local_config default value to true
  conf/nebula-metad.conf.default
  conf/nebula-metad.conf.production
  conf/nebula-storaged-listener.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
Labels: ready-for-testing

#471 Fix add host overlap with another zone's host
  src/meta/processors/zoneMan/AddZoneProcessor.cpp
  src/meta/processors/zoneMan/UpdateZoneProcessor.cpp
  src/meta/test/GroupZoneTest.cpp
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing

#472 fix zone not exist when create group
  src/meta/MetaServiceUtils.cpp
  src/meta/processors/zoneMan/AddGroupProcessor.cpp
  src/meta/test/GroupZoneTest.cpp
Labels: ready-for-testing

#480 update lastUpdateTime when term is newer
  src/meta/ActiveHostsMan.cpp
  src/storage/test/TossEnvironment.h
Labels: ready-for-testing

#461 Available disk space related changes
  src/daemons/CMakeLists.txt
  src/kvstore/CMakeLists.txt
  src/kvstore/DiskManager.cpp
  src/kvstore/DiskManager.h
  src/kvstore/EventListener.h
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/PartManager.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/plugins/elasticsearch/ESListener.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/test/CMakeLists.txt
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/test/CMakeLists.txt
  src/kvstore/test/DiskManagerTest.cpp
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/test/CMakeLists.txt
  src/kvstore/wal/test/FileBasedWalTest.cpp
  src/kvstore/wal/test/WalFileIterTest.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/processors/admin/AdminClient.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: ready-for-testing

#484 unify reset/cleanup usage in Listener/Part
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/Part.h
  src/kvstore/raftex/RaftPart.h
Labels: ready-for-testing

#488 Avoid the conversion between folly::StringPiece and std::string.
  src/codec/RowWriterV2.cpp
  src/codec/RowWriterV2.h
  src/codec/test/ResultSchemaProvider.cpp
  src/codec/test/ResultSchemaProvider.h
Labels: ready-for-testing

#466 use docker cache for docker build
  docker/Dockerfile
Labels: ready-for-testing

#490 add listener conf file for make install
  conf/CMakeLists.txt
Labels: ready-for-testing

#486 fix report error when field type and value not match in update edge
  src/storage/exec/UpdateNode.h
  src/storage/test/UpdateEdgeTest.cpp
  src/storage/test/UpdateVertexTest.cpp
Labels: ready-for-testing

#483 return empty when the TagName OR edgeName of current row is different…
  src/storage/context/StorageExpressionContext.cpp
Labels: ready-for-testing

#497 fix typo
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
Labels: ready-for-testing

#500 fix use incorrect lock
  src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
Labels: ready-for-testing

#502 fix balance thread hang up
  src/kvstore/wal/FileBasedWal.cpp
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
Labels: ready-for-testing

#358 PlainTable support
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/daemons/StorageDaemon.cpp
  src/kvstore/KVEngine.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/test/NebulaStoreTest.cpp
  src/kvstore/test/RocksEngineConfigTest.cpp
  src/kvstore/test/RocksEngineTest.cpp
  src/mock/MockCluster.cpp
  src/storage/StorageServer.cpp
  src/storage/StorageServer.h
  src/storage/test/GetPropTest.cpp
  src/tools/db-upgrade/DbUpgrader.cpp
Labels: ready-for-testing

#438 Raft heartbeat process in event base
  src/kvstore/KVEngine.h
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/Host.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/RaftexService.h
  src/kvstore/raftex/test/LeaderTransferTest.cpp
  src/kvstore/raftex/test/TestShard.cpp
  src/kvstore/raftex/test/TestShard.h
Labels: depend on common, ready-for-testing

#481 Refactor expression pointer usage
  src/codec/RowWriterV2.cpp
  src/codec/test/ResultSchemaProvider.cpp
  src/codec/test/ResultSchemaProvider.h
  src/codec/test/RowWriterV2Test.cpp
  src/meta/processors/schemaMan/SchemaUtil.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/meta/upgradeData/MetaDataUpgrade.cpp
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/mock/MockData.cpp
  src/mock/MockData.h
  src/storage/CommonUtils.h
  src/storage/context/StorageExpressionContext.cpp
  src/storage/context/StorageExpressionContext.h
  src/storage/exec/FilterNode.h
  src/storage/exec/QueryUtils.h
  src/storage/exec/UpdateNode.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/test/AddAndUpdateVertexAndEdgeBenchmark.cpp
  src/storage/test/GetNeighborsBenchmark.cpp
  src/storage/test/GetNeighborsTest.cpp
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/IndexWriteTest.cpp
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/UpdateEdgeTest.cpp
  src/storage/test/UpdateVertexTest.cpp
  src/storage/test/VertexCacheTest.cpp
Labels: depend on common, enhancement, ready-for-testing

#509 replace std::filesystem with boost::filesystem
  src/kvstore/DiskManager.cpp
  src/kvstore/DiskManager.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/test/DiskManagerTest.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/processors/admin/GetMetaDirInfoProcessor.cpp
  src/storage/admin/ListClusterInfoProcessor.cpp
Labels: ready-for-testing

#505 Fit the modification of expose time utils.
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/tools/meta-dump/MetaDumpTool.cpp
Labels: ready-for-testing

#507 Modify cmake require version
  CMakeLists.txt
Labels: ready-for-testing

#493 Update nebula-storaged-listener.conf.production
  conf/nebula-storaged-listener.conf.production
Labels: ready-for-testing
