Repository vesoft-inc/nebula-storage, pull requests merged in 2021-02, with the labels that each got.

#341 Fix wrong log info, should be rootPath
  src/kvstore/NebulaStore.cpp
Labels: Ready-to-review, ready-for-testing

#340 fix meta version invalid when upgrade from 2.0-alpha/rc1
  src/meta/MetaVersionMan.cpp
Labels: Ready-to-review, ready-for-testing

#329 Remove duplicate rocksdb_block_cache config.
  conf/nebula-storaged.conf.production
Labels: ready-for-testing

#342 Refactored the stats
  src/kvstore/wal/test/WalFileIterTest.cpp
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/BaseProcessor.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/admin/HBProcessor.h
  src/meta/test/HBProcessorTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/storage/BaseProcessor.h
  src/storage/CommonUtils.h
  src/storage/GeneralStorageServiceHandler.cpp
  src/storage/GeneralStorageServiceHandler.h
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/GraphStorageServiceHandler.h
  src/storage/InternalStorageServiceHandler.cpp
  src/storage/InternalStorageServiceHandler.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupProcessor.cpp
  src/storage/index/LookupProcessor.h
  src/storage/kv/GetProcessor.cpp
  src/storage/kv/GetProcessor.h
  src/storage/kv/PutProcessor.cpp
  src/storage/kv/PutProcessor.h
  src/storage/kv/RemoveProcessor.cpp
  src/storage/kv/RemoveProcessor.h
  src/storage/mutate/AddEdgesAtomicProcessor.cpp
  src/storage/mutate/AddEdgesAtomicProcessor.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.h
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/GetPropProcessor.h
  src/storage/query/GetUUIDProcessor.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/query/ScanVertexProcessor.h
  src/storage/transaction/GetValueProcessor.cpp
  src/storage/transaction/GetValueProcessor.h
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionProcessor.cpp
  src/storage/transaction/TransactionProcessor.h
Labels: ready-for-testing

#348 adjust rocksdb compaction parameter
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
Labels: Ready-to-review, ready-for-testing

#346 Memory Lock, based on folly::ConcurrentHashMap
  src/storage/test/CMakeLists.txt
  src/storage/test/MemoryLockTest.cpp
  src/utils/MemoryLockCore.h
  src/utils/MemoryLockWrapper.h
Labels: Ready-to-review, ready-for-testing

#349 Config the upgrade string index key length limit.
  src/meta/MetaVersionMan.cpp
  src/meta/upgradeData/MetaDataUpgrade.cpp
Labels: ready-for-testing

#333 Data Upgrader Tool
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/meta/upgradeData/MetaDataUpgrade.cpp
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  src/tools/db-upgrade/DbUpgraderTool.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV2.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV2.h
  src/utils/NebulaKeyUtils.cpp
  src/utils/NebulaKeyUtils.h
  src/utils/Types.h
  src/utils/test/NebulaKeyUtilsTest.cpp
Labels: Ready-to-review, ready-for-testing

#287 Support part distribute
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/meta/processors/jobMan/StatisJobExecutor.h
  src/mock/AdHocSchemaManager.h
  src/mock/MockCluster.cpp
  src/storage/admin/StatisTask.cpp
Labels: Ready-to-review, ready-for-testing

#356 When get index fails, report an error
  src/storage/mutate/AddEdgesAtomicProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/tools/db-upgrade/DbUpgrader.h
Labels: Ready-to-review, ready-for-testing

#351 Encode rank to make key string in order.
  src/utils/IndexKeyUtils.cpp
  src/utils/IndexKeyUtils.h
  src/utils/NebulaKeyUtils.cpp
  src/utils/NebulaKeyUtils.h
  src/utils/test/IndexKeyUtilsTest.cpp
  src/utils/test/NebulaKeyUtilsTest.cpp
Labels: Ready-to-review, ready-for-testing

#343 meta dump tool
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/tools/CMakeLists.txt
  src/tools/edges-dump/EdgesDumpTool.cpp
  src/tools/meta-dump/CMakeLists.txt
  src/tools/meta-dump/MetaDumpTool.cpp
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: Ready-to-review, ready-for-testing

#353 Unify all getActiveHosts using heartbeat_interval_secs
  src/meta/ActiveHostsMan.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/partsMan/ListPartsProcessor.cpp
  src/meta/processors/zoneMan/AddZoneProcessor.cpp
  src/meta/processors/zoneMan/UpdateZoneProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/BalanceIntegrationTest.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: Ready-to-review, ready-for-testing

#355 Improved performance with index for insert, delete and update
  src/kvstore/Common.h
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/mock/MockCluster.cpp
  src/storage/BaseProcessor.inl
  src/storage/CommonUtils.h
  src/storage/StorageServer.cpp
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.h
  src/storage/test/MemoryLockTest.cpp
  src/utils/MemoryLockWrapper.h
Labels: Ready-to-review, ready-for-testing

#361 Fix the tag write logical with index.
  src/storage/mutate/AddVerticesProcessor.cpp
Labels: bug, ready-for-testing

#360 Filter edge lock when getting edge
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/StatisTask.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/CompactionTest.cpp
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/TestUtils.h
Labels: Ready-to-review, ready-for-testing

#359 Memory lock benchmark
  src/storage/test/CMakeLists.txt
  src/storage/test/MemoryLockBenchmark.cpp
Labels: Ready-to-review, ready-for-testing

#366 IngestHandler will not set any host into storageIPs
  src/meta/MetaHttpIngestHandler.cpp
Labels: Ready-to-review, ready-for-testing
