Repository vesoft-inc/nebula-storage, pull requests merged in 2021-03, with the labels that each got.

#365 update using reader pool
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/test/VertexCacheTest.cpp
Labels: Ready-to-review, ready-for-testing

#337 re-organize compaction filter
  src/storage/CompactionFilter.h
  src/storage/test/CompactionTest.cpp
  src/utils/NebulaKeyUtils.h
Labels: Ready-to-review, ready-for-testing

#345 Fix snapshot promise
  src/kvstore/SnapshotManagerImpl.cpp
  src/kvstore/SnapshotManagerImpl.h
  src/kvstore/raftex/Host.cpp
  src/kvstore/raftex/SnapshotManager.cpp
  src/kvstore/raftex/SnapshotManager.h
  src/storage/GraphStorageServiceHandler.cpp
Labels: Ready-to-review, ready-for-testing

#371 Unfreeze the limit of SST part-file's size
  src/meta/MetaHttpDownloadHandler.cpp
Labels: Ready-to-review, ready-for-testing

#370 forbid SO_REUSEPORT
  src/daemons/MetaDaemon.cpp
  src/kvstore/raftex/RaftexService.cpp
  src/storage/StorageServer.cpp
Labels: Ready-to-review, ready-for-testing

#364 update iterate edges benchmark
  src/codec/RowReaderV2.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/test/ScanEdgePropBenchmark.cpp
Labels: Ready-to-review, ready-for-testing

#373 remove shuffle when balance data
  src/meta/processors/admin/Balancer.cpp
Labels: Ready-to-review, ready-for-testing

#368 code improved for parameter copy
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/Part.cpp
  src/kvstore/Part.h
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
  src/storage/transaction/TransactionProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#352 change toBool
  src/storage/exec/FilterNode.h
Labels: Ready-to-review, ready-for-testing

#357 Correct the sha in http server.
  src/codec/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemon.cpp
  src/daemons/StorageDaemon.cpp
  src/kvstore/test/CMakeLists.txt
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/GetStatisTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/meta/test/TestUtils.h
  src/storage/StorageServer.cpp
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
  src/version/CMakeLists.txt
  src/version/Version.cpp.in
  src/version/Version.h
  src/version/test/CMakeLists.txt
  src/version/test/StatusHandlerTest.cpp
Labels: Ready-to-review, bug, ready-for-testing

#374 unify heartbeat_interval_secs in meta conf and storage conf
  conf/nebula-storaged-listener.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
Labels: Ready-to-review, ready-for-testing

#354 Make flags/stats/status HTTP API confirm to RESTful specification
  .gitignore
  src/storage/test/StorageHttpAdminHandlerTest.cpp
  src/storage/test/StorageHttpStatsHandlerTest.cpp
Labels: Ready-to-review, in-progress, ready-for-testing

#376 fix early onFinished
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/CommonUtils.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.h
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.h
  src/storage/transaction/TransactionManager.cpp
Labels: Ready-to-review, ready-for-testing

#362 Improve the expired time for hosts to avoid mistake.
  src/meta/ActiveHostsMan.cpp
  src/meta/processors/listenerMan/ListenerProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/BalanceIntegrationTest.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: Ready-to-review, ready-for-testing

#322 1 Add max_concurrent configuration for OSS (-jobs )
  util/br/cmd/backup.go
  util/br/cmd/restore.go
  util/br/config/backup_example.yaml
  util/br/pkg/backup/backup.go
  util/br/pkg/config/config.go
  util/br/pkg/remote/ssh.go
  util/br/pkg/restore/restore.go
  util/br/pkg/storage/hdfs.go
  util/br/pkg/storage/local.go
  util/br/pkg/storage/oss.go
  util/br/pkg/storage/s3.go
  util/br/pkg/storage/s3_test.go
  util/br/pkg/storage/storage.go
  util/br/pkg/storage/storage_test.go
Labels: Ready-to-review, doc required, ready-for-testing

#378 Set heartbeat log level to debug level
  src/meta/processors/admin/HBProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#380 Fixed crash error for TTL
  src/storage/CommonUtils.cpp
Labels: Ready-to-review, ready-for-testing

#331 Improve delete edges, remove extra prefix in fetch
  src/meta/test/MetaClientTest.cpp
  src/storage/BaseProcessor.h
  src/storage/BaseProcessor.inl
  src/storage/exec/GetPropNode.h
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/test/VertexCacheTest.cpp
Labels: Ready-to-review, ready-for-testing

#383 Added timestamp to data val
  src/codec/RowReader.h
  src/codec/RowReaderV1.cpp
  src/codec/RowReaderV1.h
  src/codec/RowReaderV2.cpp
  src/codec/RowReaderV2.h
  src/codec/RowReaderWrapper.h
  src/codec/RowWriterV2.cpp
  src/codec/test/RowWriterV2Test.cpp
Labels: Ready-to-review, ready-for-testing

#165 Move the files instead of copying when ingest SST files
  src/kvstore/RocksEngine.cpp
Labels: Ready-to-review, ready-for-testing

#391 fix bug in balance data
  src/kvstore/wal/AtomicLogBuffer.h
  src/utils/NebulaKeyUtils.cpp
Labels: Ready-to-review, ready-for-testing

#387 speed up first election
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
Labels: Ready-to-review, ready-for-testing

#395 Delete the BR tool (move to https://github.com/vesoft-inc/nebula-br).
  util/br/Makefile
  util/br/cmd/backup.go
  util/br/cmd/cleanup.go
  util/br/cmd/cmd.go
  util/br/cmd/restore.go
  util/br/cmd/validate.go
  util/br/cmd/validate_test.go
  util/br/cmd/version.go
  util/br/config/backup_example.yaml
  util/br/config/restore_example.yaml
  util/br/go.mod
  util/br/go.sum
  util/br/main.go
  util/br/pkg/backup/backup.go
  util/br/pkg/cleanup/cleanup.go
  util/br/pkg/config/config.go
  util/br/pkg/metaclient/meta.go
  util/br/pkg/metaclient/util.go
  util/br/pkg/remote/ssh.go
  util/br/pkg/restore/restore.go
  util/br/pkg/storage/hdfs.go
  util/br/pkg/storage/local.go
  util/br/pkg/storage/oss.go
  util/br/pkg/storage/s3.go
  util/br/pkg/storage/s3_test.go
  util/br/pkg/storage/storage.go
  util/br/pkg/storage/storage_test.go
Labels: Ready-to-review, ready-for-testing

#392 Upgrade tool forced type conversion
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
Labels: Ready-to-review, ready-for-testing

#397 fix use wrong error code
  src/storage/mutate/AddVerticesProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#398 cherrypick #391 #387 ##395 #392 #397
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/kvstore/wal/AtomicLogBuffer.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/tools/db-upgrade/DbUpgrader.cpp
  src/tools/db-upgrade/DbUpgrader.h
  src/utils/NebulaKeyUtils.cpp
  util/br/Makefile
  util/br/cmd/backup.go
  util/br/cmd/cleanup.go
  util/br/cmd/cmd.go
  util/br/cmd/restore.go
  util/br/cmd/validate.go
  util/br/cmd/validate_test.go
  util/br/cmd/version.go
  util/br/config/backup_example.yaml
  util/br/config/restore_example.yaml
  util/br/go.mod
  util/br/go.sum
  util/br/main.go
  util/br/pkg/backup/backup.go
  util/br/pkg/cleanup/cleanup.go
  util/br/pkg/config/config.go
  util/br/pkg/metaclient/meta.go
  util/br/pkg/metaclient/util.go
  util/br/pkg/remote/ssh.go
  util/br/pkg/restore/restore.go
  util/br/pkg/storage/hdfs.go
  util/br/pkg/storage/local.go
  util/br/pkg/storage/oss.go
  util/br/pkg/storage/s3.go
  util/br/pkg/storage/s3_test.go
  util/br/pkg/storage/storage.go
  util/br/pkg/storage/storage_test.go
Labels: Ready-to-review, ready-for-testing

#385 [DO NOT MERGE] refactor agg
  src/codec/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
  src/tools/db-dump/CMakeLists.txt
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/meta-dump/CMakeLists.txt
  src/tools/simple-kv-verify/CMakeLists.txt
  src/tools/storage-perf/CMakeLists.txt
Labels: Ready-to-review, ready-for-testing

#396 removed resource in storage, just use graph's when package
  CMakeLists.txt
  resources/CMakeLists.txt
  resources/gflags.json
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
Labels: Ready-to-review, ready-for-testing

#401 Corrected template for listener
  conf/nebula-storaged-listener.conf.production
Labels: Ready-to-review, doc required, ready-for-testing

#400 apply change loadLeader
  src/storage/test/TossEnvironment.h
Labels: Ready-to-review, ready-for-testing

#406 JobManager should use last para of job paras to identify space name, not first
  src/meta/processors/jobMan/JobManager.cpp
Labels: Ready-to-review, ready-for-testing

#403 Generate log directory, if it does not exist
  conf/nebula-metad.conf.default
  conf/nebula-metad.conf.production
  conf/nebula-storaged-listener.conf.production
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/daemons/SetupLogging.cpp
Labels: Ready-to-review, ready-for-testing

#379 Support negative correlativity
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/storage/admin/StatisTask.cpp
Labels: Ready-to-review, depend on common, ready-for-testing

#408 fix index data loss when insert data during rebuilding index
  src/storage/CommonUtils.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
Labels: ready-for-testing

#384 [Doc] Update README
  README-CN.md
  README.md
  docs/logo.png
Labels: Ready-to-review, ready-for-testing

#344 Use absolute path for nebula binary and config file in docker image
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
Labels: ready-for-testing

#410 Fix readme document
  README-CN.md
  README.md
Labels: Ready-to-review, ready-for-testing

#412 read from leader for meta
  src/daemons/MetaDaemon.cpp
  src/kvstore/NebulaStore.cpp
Labels: Ready-to-review, ready-for-testing

#386 Push down some expressions to the storage layer
  src/storage/context/StorageExpressionContext.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
Labels: ready-for-testing

#389 build nebula tools image
  docker/Dockerfile.tools
  docker/README.md
Labels: Ready-to-review, ready-for-testing
