Repository vesoft-inc/nebula-storage, pull requests merged in 2021-04, with the labels that each got.

#417 Fix bug: when a zone has multiple hosts, zoneName will be moved multi…
  src/meta/processors/admin/Balancer.cpp
Labels: Ready-to-review, ready-for-testing

#419 add some more log, if job dispatch failed.
  src/meta/processors/jobMan/MetaJobExecutor.cpp
Labels: Ready-to-review, ready-for-testing

#415 build nebula-tools docker image nightly
  .github/workflows/docker.yml
Labels: ready-for-testing

#424 Revert "read from leader for meta"
  src/daemons/MetaDaemon.cpp
  src/kvstore/NebulaStore.cpp
Labels: Ready-to-review, ready-for-testing

#426 check type of index
  src/meta/processors/indexMan/GetEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/GetTagIndexProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#420 Fix core issue: for a new host with no partition, can't find it from …
  src/meta/processors/admin/Balancer.cpp
Labels: Ready-to-review, ready-for-testing

#422 Specify nebula common branch when checkout
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#428 restore update atomic operation
  src/storage/exec/UpdateNode.h
Labels: Ready-to-review, ready-for-testing

#430 Fix cleanWAL block raft heartbeat
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftexService.cpp
  src/kvstore/raftex/test/SnapshotTest.cpp
  src/kvstore/wal/FileBasedWal.cpp
  src/kvstore/wal/FileBasedWal.h
  src/kvstore/wal/test/FileBasedWalTest.cpp
  src/utils/OperationKeyUtils.cpp
Labels: Ready-to-review, ready-for-testing

#427 cherrypick #426 #422 #428
  .github/workflows/pull_request.yml
  src/meta/processors/indexMan/GetEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/GetTagIndexProcessor.cpp
  src/storage/exec/UpdateNode.h
Labels: ready-for-testing

#382 Support TTL for index
  src/meta/processors/BaseProcessor.h
  src/meta/processors/BaseProcessor.inl
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
  src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
  src/meta/processors/schemaMan/AlterTagProcessor.cpp
  src/meta/test/ProcessorTest.cpp
  src/storage/CommonUtils.cpp
  src/storage/CommonUtils.h
  src/storage/CompactionFilter.h
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/UpdateNode.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/test/CMakeLists.txt
  src/storage/test/CompactionTest.cpp
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/QueryTestUtils.h
  src/utils/IndexKeyUtils.cpp
  src/utils/IndexKeyUtils.h
Labels: Ready-to-review, doc required, ready-for-testing

#418 send leader term with heart and reorganize leader table
  src/kvstore/KVStore.h
  src/kvstore/ListenerFactory.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/kvstore/raftex/RaftPart.h
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/jobMan/MetaJobExecutor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.h
  src/meta/processors/partsMan/ListPartsProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/GetStatisTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/MetaServiceUtilsTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/storage/admin/AdminProcessor.h
Labels: Ready-to-review, ready-for-testing

#411 Add comment field for schema.
  src/meta/MetaServiceUtils.cpp
  src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
  src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
Labels: ready-for-testing

#437 Revert "send leader term with heart and reorganize leader table"
  src/kvstore/KVStore.h
  src/kvstore/ListenerFactory.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/kvstore/raftex/RaftPart.h
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/jobMan/MetaJobExecutor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.h
  src/meta/processors/partsMan/ListPartsProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/GetStatisTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/MetaServiceUtilsTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/storage/admin/AdminProcessor.h
Labels: Ready-to-review, ready-for-testing

#413 insert vertex & edge if not exists
  src/mock/MockData.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/test/AddAndUpdateVertexAndEdgeBenchmark.cpp
  src/storage/test/ElasticSearchBulkInsertTest.cpp
  src/storage/test/IndexWithTTLTest.cpp
  src/storage/test/IndexWriteTest.cpp
  src/storage/test/LookupIndexTest.cpp
  src/tools/storage-perf/StorageIntegrityTool.cpp
Labels: Ready-to-review, depend on common, ready-for-testing

#439 Reorg leader table with graph ci fix
  src/kvstore/KVStore.h
  src/kvstore/ListenerFactory.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/PartManager.cpp
  src/kvstore/PartManager.h
  src/kvstore/raftex/RaftPart.h
  src/kvstore/test/NebulaListenerTest.cpp
  src/kvstore/test/NebulaStoreTest.cpp
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/jobMan/MetaJobExecutor.cpp
  src/meta/processors/jobMan/MetaJobExecutor.h
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.h
  src/meta/processors/partsMan/ListPartsProcessor.cpp
  src/meta/test/ActiveHostsManTest.cpp
  src/meta/test/GetStatisTest.cpp
  src/meta/test/MetaClientTest.cpp
  src/meta/test/MetaServiceUtilsTest.cpp
  src/meta/test/ProcessorTest.cpp
  src/storage/admin/AdminProcessor.h
Labels: Ready-to-review, ready-for-testing

#440 get all latest version edge schema
  src/mock/AdHocSchemaManager.cpp
  src/mock/AdHocSchemaManager.h
Labels: Ready-to-review, depend on common, ready-for-testing

#443 Optimize to improve query performance
  src/meta/processors/partsMan/ListPartsProcessor.cpp
  src/meta/processors/partsMan/ListPartsProcessor.h
Labels: Ready-to-review, ready-for-testing

#431 Storage CI build stability
  .github/workflows/pull_request.yml
  src/meta/test/CMakeLists.txt
  src/meta/test/IndexProcessorTest.cpp
  src/meta/test/ProcessorTest.cpp
Labels: Ready-to-review, ready-for-testing

#445 Supplement part of the missing ut
  src/meta/test/ProcessorTest.cpp
Labels: Ready-to-review, ready-for-testing

#446 fix 1 replica balance failed, rebuild index ut
  src/storage/admin/AdminProcessor.h
  src/storage/test/RebuildIndexTest.cpp
Labels: Ready-to-review, doc required, ready-for-testing

#444 Ignore the int float conversion warning.
  src/codec/RowWriterV2.cpp
Labels: Ready-to-review, ready-for-testing

#451 only support one edge int update
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/query/QueryBaseProcessor.inl
  src/storage/test/UpdateEdgeTest.cpp
  src/storage/test/UpdateVertexTest.cpp
Labels: Ready-to-review, ready-for-testing

#268 Modify the createcheckpoint interface of storage
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/raftex/RaftPart.cpp
  src/kvstore/raftex/RaftPart.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/AdminClient.h
  src/meta/processors/admin/CreateBackupProcessor.cpp
  src/meta/processors/admin/SnapShot.cpp
  src/meta/processors/admin/SnapShot.h
  src/meta/test/CreateBackupProcessorTest.cpp
  src/meta/test/MockAdminClient.h
  src/storage/admin/CreateCheckpointProcessor.cpp
Labels: ready-for-testing

#455 Example of folly::enumerate
  src/storage/index/LookupBaseProcessor.inl
Labels: ready-for-testing

#454 fix show hosts errors
  src/meta/processors/partsMan/DropSpaceProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.h
  src/tools/meta-dump/MetaDumpTool.cpp
Labels: ready-for-testing
