Repository vesoft-inc/nebula-storage, pull requests merged in 2021-01, with the labels that each got.

#247 1 Move the configuration of the BR tool to the config directory
  util/br/config/backup_example.yaml
  util/br/config/restore_example.yaml
Labels: Ready-to-review, doc required, ready-for-testing

#283 Added backup for __indexes__ tables.
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/test/CreateBackupProcessorTest.cpp
Labels: Ready-to-review, ready-for-testing

#282 Fix some issue in balance data
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/test/BalancerTest.cpp
Labels: Ready-to-review, ready-for-testing

#290 fix map erase
  src/meta/processors/admin/Balancer.cpp
Labels: Ready-to-review, ready-for-testing

#289 change dockerfile expose
  docker/Dockerfile.metad
  docker/Dockerfile.storaged
Labels: ready-for-testing

#230 dedup result for index scan
  src/storage/exec/DeDupNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/QueryUtils.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/test/LookupIndexTest.cpp
Labels: Ready-to-review, ready-for-testing

#294 fix download and ingest caused problem
  src/codec/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/test/CMakeLists.txt
  src/storage/test/CMakeLists.txt
Labels: Ready-to-review, ready-for-testing

#296 Fix raft bugs
  src/kvstore/raftex/RaftPart.cpp
Labels: Ready-to-review, ready-for-testing

#295 Support multi rebuild index
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/test/RebuildIndexTest.cpp
Labels: Ready-to-review, doc required, ready-for-testing

#297 Fix index task to directly to get tag index
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildEdgeIndexTask.h
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/admin/RebuildIndexTask.h
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.h
Labels: ready-for-testing

#284 Fixed a backup bug
  src/meta/processors/admin/SnapShot.cpp
  src/meta/test/CreateBackupProcessorTest.cpp
Labels: Ready-to-review, ready-for-testing

#277 Added max_concurrent configuration for BR
  util/br/cmd/backup.go
  util/br/cmd/validate.go
  util/br/config/backup_example.yaml
  util/br/pkg/backup/backup.go
  util/br/pkg/config/config.go
  util/br/pkg/remote/ssh.go
  util/br/pkg/restore/restore.go
Labels: Ready-to-review, doc required, ready-for-testing

#299 add max_edge_returned_per_vertex flag
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/test/GetNeighborsTest.cpp
Labels: Ready-to-review, ready-for-testing

#291 fixed the bug for restore meta.
  src/kvstore/KVStore.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/admin/RestoreProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#288 add implementation of getAllLatestTagSchema()
  src/mock/AdHocSchemaManager.cpp
  src/mock/AdHocSchemaManager.h
Labels: Ready-to-review, ready-for-testing

#292 Task report finish to job manager
  src/meta/CMakeLists.txt
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/jobMan/AdminJobProcessor.cpp
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/processors/jobMan/MetaJobExecutor.cpp
  src/meta/processors/jobMan/MetaJobExecutor.h
  src/meta/processors/jobMan/ReportTaskProcessor.cpp
  src/meta/processors/jobMan/ReportTaskProcessor.h
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/meta/processors/jobMan/StatisJobExecutor.h
  src/meta/processors/jobMan/TaskDescription.h
  src/meta/test/GetStatisTest.cpp
  src/meta/test/JobManagerTest.cpp
  src/storage/admin/AdminTaskProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#134 Support to update meta data from 1.0 to 2.0
  src/daemons/CMakeLists.txt
  src/daemons/MetaDaemon.cpp
  src/meta/ActiveHostsMan.h
  src/meta/CMakeLists.txt
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
  src/meta/processors/admin/CreateSnapshotProcessor.cpp
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/jobMan/JobDescription.cpp
  src/meta/processors/jobMan/JobUtils.cpp
  src/meta/upgradeData/CMakeLists.txt
  src/meta/upgradeData/MetaDataUpgrade.cpp
  src/meta/upgradeData/MetaDataUpgrade.h
  src/meta/upgradeData/oldThrift/CMakeLists.txt
  src/meta/upgradeData/oldThrift/MetaServiceUtilsV1.cpp
  src/meta/upgradeData/oldThrift/MetaServiceUtilsV1.h
  src/meta/upgradeData/oldThrift/old_meta.thrift
Labels: ready-for-testing

#298 Modify to support to rebuild multi indexes
  src/meta/processors/jobMan/ListEdgeIndexStatusProcessor.cpp
  src/meta/processors/jobMan/ListTagIndexStatusProcessor.cpp
  src/meta/processors/jobMan/RebuildEdgeJobExecutor.cpp
  src/meta/processors/jobMan/RebuildJobExecutor.cpp
  src/meta/processors/jobMan/RebuildJobExecutor.h
  src/meta/processors/jobMan/RebuildTagJobExecutor.cpp
  src/storage/admin/RebuildIndexTask.cpp
  src/storage/test/RebuildIndexTest.cpp
Labels: ready-for-testing

#302 if response of reportTaskFinish() didn't have value, AdminTaskProcessor may core
  src/storage/admin/AdminTaskProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#300 Update the limit lower bound check.
  src/storage/exec/GetNeighborsNode.h
  src/storage/query/GetNeighborsProcessor.cpp
Labels: ready-for-testing

#304 Bugfix, if some job failed, job manager will stop scheduling the left jobs.
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/test/GetStatisTest.cpp
Labels: ready-for-testing

#303 Fix rewrite job's time
  src/meta/upgradeData/MetaDataUpgrade.cpp
Labels: ready-for-testing

#308 Fix the use after free.
  src/storage/admin/AdminTaskProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#310 fix read readerV1 data from cache
  src/codec/RowReaderV1.cpp
  src/codec/RowReaderV1.h
Labels: Ready-to-review, ready-for-testing

#315 Fix RowReaderV1 with unknown prop
  src/codec/RowReaderV1.cpp
Labels: ready-for-testing

#314 Fix delete index
  src/meta/MetaVersionMan.cpp
Labels: ready-for-testing

#309 Support multiple versions of schemas for index scan
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexFilterNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
Labels: Ready-to-review, ready-for-testing

#317 fix limit type to int64
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
Labels: Ready-to-review, ready-for-testing

#321 2 quick fix for 2.0 ga test.
  src/meta/processors/jobMan/RebuildJobExecutor.cpp
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/storage/admin/AdminTaskManager.cpp
Labels: Ready-to-review, ready-for-testing

#318 Using executor pool for all scan interfaces
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupProcessor.cpp
  src/storage/index/LookupProcessor.h
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/GetPropProcessor.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanEdgeProcessor.h
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/query/ScanVertexProcessor.h
  src/storage/test/GetNeighborsTest.cpp
  src/storage/test/VertexCacheTest.cpp
Labels: Ready-to-review, ready-for-testing

#320 fix multi meta upgrade
  src/daemons/MetaDaemon.cpp
  src/meta/MetaVersionMan.cpp
  src/meta/MetaVersionMan.h
Labels: Ready-to-review, ready-for-testing

#323 Pass by value instead of pass by reference
  src/storage/index/LookupProcessor.cpp
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
Labels: Ready-to-review, ready-for-testing

#235 Zone balance data
  src/codec/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/kvstore/test/CMakeLists.txt
  src/meta/ActiveHostsMan.cpp
  src/meta/ActiveHostsMan.h
  src/meta/CMakeLists.txt
  src/meta/MetaServiceUtils.cpp
  src/meta/processors/admin/BalancePlan.cpp
  src/meta/processors/admin/BalancePlan.h
  src/meta/processors/admin/BalanceProcessor.cpp
  src/meta/processors/admin/BalanceTask.cpp
  src/meta/processors/admin/BalanceTask.h
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/admin/Balancer.h
  src/meta/processors/admin/LeaderBalanceProcessor.cpp
  src/meta/processors/jobMan/BalanceJobExecutor.cpp
  src/meta/processors/jobMan/BalanceJobExecutor.h
  src/meta/processors/jobMan/JobManager.cpp
  src/meta/processors/jobMan/JobManager.h
  src/meta/processors/jobMan/StatisJobExecutor.cpp
  src/meta/processors/partsMan/CreateSpaceProcessor.cpp
  src/meta/processors/zoneMan/UpdateZoneProcessor.cpp
  src/meta/test/BalancerTest.cpp
  src/meta/test/CMakeLists.txt
  src/meta/test/MetaClientTest.cpp
  src/meta/test/MetaHttpReplaceHandlerTest.cpp
  src/meta/test/TestUtils.h
  src/mock/MockCluster.cpp
  src/mock/MockCluster.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/test/CMakeLists.txt
  src/storage/test/CompactionTest.cpp
  src/storage/test/ElasticSearchBulkInsertTest.cpp
  src/storage/test/KVClientTest.cpp
  src/storage/test/StorageClientTest.cpp
  src/storage/test/TossEnvironment.h
  src/storage/transaction/GetValueProcessor.cpp
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionProcessor.cpp
Labels: ready-for-testing

#319 performance optimize, if disable mvcc, may ignore some storage iterator check.
  src/storage/exec/StorageIterator.h
Labels: Ready-to-review, ready-for-testing

#328 Upgrade the meta index info.
  src/meta/MetaVersionMan.cpp
  src/meta/upgradeData/MetaDataUpgrade.cpp
  src/meta/upgradeData/MetaDataUpgrade.h
Labels: ready-for-testing

#326 separate vertex and edge
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/SnapshotManagerImpl.cpp
  src/kvstore/SnapshotManagerImpl.h
  src/kvstore/plugins/elasticsearch/ESListener.cpp
  src/storage/CompactionFilter.h
  src/storage/admin/RebuildEdgeIndexTask.cpp
  src/storage/admin/RebuildTagIndexTask.cpp
  src/storage/admin/StatisTask.cpp
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/CompactionTest.cpp
  src/storage/test/IndexWriteTest.cpp
  src/storage/test/RebuildIndexTest.cpp
  src/storage/test/StatisTaskTest.cpp
  src/tools/CMakeLists.txt
  src/tools/db-dump/DbDumper.cpp
  src/tools/db-upgrade/CMakeLists.txt
  src/tools/db-upgrade/DbUpgraderTool.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.cpp
  src/tools/db-upgrade/NebulaKeyUtilsV1.h
  src/utils/NebulaKeyUtils.cpp
  src/utils/NebulaKeyUtils.h
  src/utils/Types.h
  src/utils/test/NebulaKeyUtilsTest.cpp
Labels: Ready-to-review, ready-for-testing

#327 pass vIdLen to init RocksEngine, to support 2.0 variable length prefix bloom filter.
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngine.h
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/test/NebulaStoreTest.cpp
  src/kvstore/test/RocksEngineConfigTest.cpp
  src/kvstore/test/RocksEngineTest.cpp
Labels: ready-for-testing

#332 const VertexID&
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/utils/IndexKeyUtils.cpp
  src/utils/IndexKeyUtils.h
  src/utils/NebulaKeyUtils.cpp
  src/utils/NebulaKeyUtils.h
  src/utils/OperationKeyUtils.cpp
  src/utils/OperationKeyUtils.h
Labels: Ready-to-review, ready-for-testing

#335 fix upgrade index info
  src/meta/upgradeData/MetaDataUpgrade.cpp
Labels: Ready-to-review, ready-for-testing

#334 1st change edge ver from i64 to char;
  src/kvstore/plugins/hbase/CMakeLists.txt
  src/kvstore/plugins/hbase/HBaseStore.cpp
  src/kvstore/plugins/hbase/test/HBaseStoreTest.cpp
  src/storage/CompactionFilter.h
  src/storage/exec/IndexVertexNode.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/TagNode.h
  src/storage/exec/UpdateNode.h
  src/storage/mutate/AddEdgesAtomicProcessor.cpp
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/query/ScanEdgeProcessor.cpp
  src/storage/query/ScanVertexProcessor.cpp
  src/storage/test/AddAndUpdateVertexAndEdgeBenchmark.cpp
  src/storage/test/AddEdgesTest.cpp
  src/storage/test/AddVerticesTest.cpp
  src/storage/test/CompactionTest.cpp
  src/storage/test/DeleteEdgesTest.cpp
  src/storage/test/DeleteVerticesTest.cpp
  src/storage/test/GetNeighborsTest.cpp
  src/storage/test/IndexWriteTest.cpp
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/PrefixBloomFilterBenchmark.cpp
  src/storage/test/QueryTestUtils.h
  src/storage/test/ScanEdgeTest.cpp
  src/storage/test/ScanVertexTest.cpp
  src/storage/test/TestUtils.h
  src/storage/test/TossEnvironment.h
  src/storage/test/TossTest.cpp
  src/storage/test/UpdateVertexTest.cpp
  src/storage/transaction/TossEdgeIterator.h
  src/storage/transaction/TransactionManager.cpp
  src/storage/transaction/TransactionManager.h
  src/storage/transaction/TransactionUtils.cpp
  src/storage/transaction/TransactionUtils.h
  src/tools/db-upgrade/NebulaKeyUtilsV1.h
  src/utils/NebulaKeyUtils.cpp
  src/utils/NebulaKeyUtils.h
  src/utils/Types.h
  src/utils/test/NebulaKeyUtilsTest.cpp
Labels: Ready-to-review, ready-for-testing
