Repository vesoft-inc/nebula-storage, pull requests merged in 2021-07, with the labels that each got.

#495 Slow query.
  src/meta/MetaServiceHandler.cpp
  src/meta/MetaServiceHandler.h
  src/meta/processors/sessionMan/SessionManagerProcessor.cpp
  src/meta/processors/sessionMan/SessionManagerProcessor.h
  src/meta/test/ProcessorTest.cpp
Labels: depend on common, ready-for-testing

#482 rebuild fulltext indexes via listener
  src/kvstore/Listener.cpp
  src/kvstore/Listener.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/NebulaStore.h
  src/kvstore/plugins/elasticsearch/ESListener.h
  src/meta/CMakeLists.txt
  src/meta/processors/jobMan/MetaJobExecutor.cpp
  src/meta/processors/jobMan/MetaJobExecutor.h
  src/meta/processors/jobMan/RebuildFTJobExecutor.cpp
  src/meta/processors/jobMan/RebuildFTJobExecutor.h
  src/meta/processors/jobMan/RebuildJobExecutor.h
  src/meta/processors/jobMan/StatisJobExecutor.h
  src/storage/CMakeLists.txt
  src/storage/admin/AdminTask.cpp
  src/storage/admin/RebuildFTIndexTask.cpp
  src/storage/admin/RebuildFTIndexTask.h
Labels: ready-for-testing

#432 Add version in host info.
  src/meta/ActiveHostsMan.h
  src/meta/processors/admin/HBProcessor.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
Labels: ready-for-testing

#511 Modify update time and add log
  src/meta/processors/sessionMan/SessionManagerProcessor.cpp
Labels: ready-for-testing

#512 fix disk manager thread conflict
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/kvstore/DiskManager.cpp
  src/kvstore/DiskManager.h
  src/kvstore/NebulaStore.cpp
  src/kvstore/raftex/RaftPart.cpp
Labels: bug, ready-for-testing

#503 Concurrently go/lookup/fetch
  src/storage/BaseProcessor.h
  src/storage/CommonUtils.h
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
  src/storage/exec/AggregateNode.h
  src/storage/exec/DeDupNode.h
  src/storage/exec/EdgeNode.h
  src/storage/exec/FilterNode.h
  src/storage/exec/GetNeighborsNode.h
  src/storage/exec/GetPropNode.h
  src/storage/exec/HashJoinNode.h
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexOutputNode.h
  src/storage/exec/IndexScanNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/TagNode.h
  src/storage/exec/UpdateNode.h
  src/storage/exec/UpdateResultNode.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/index/LookupProcessor.cpp
  src/storage/index/LookupProcessor.h
  src/storage/mutate/UpdateEdgeProcessor.cpp
  src/storage/mutate/UpdateEdgeProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/GetPropProcessor.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/query/QueryBaseProcessor.inl
  src/storage/test/GetNeighborsBenchmark.cpp
  src/storage/test/GetNeighborsTest.cpp
  src/storage/test/GetPropTest.cpp
  src/storage/test/LookupIndexTest.cpp
  src/storage/test/VertexCacheTest.cpp
  src/storage/transaction/TossEdgeIterator.h
Labels: doc affected, ready-for-testing

#510 code improve for build edge|tag context
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetPropProcessor.cpp
Labels: ready-for-testing

#508 Testcase for listener snapshot
  src/kvstore/test/NebulaListenerTest.cpp
Labels: ready-for-testing

#517 Improved data write logic to avoid reading dirty data
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/test/MemoryLockTest.cpp
  src/utils/MemoryLockWrapper.h
Labels: ready-for-testing

#518 Set the version to response.
  src/meta/processors/partsMan/ListHostsProcessor.cpp
Labels: bug, ready-for-testing

#516 Re-test index write performance since the concurrentMap instead of asyncAtomicOp.
  src/storage/test/CMakeLists.txt
  src/storage/test/StorageIndexWriteBenchmark.cpp
Labels: ready-for-testing

#519 Fix show stats
  conf/nebula-storaged.conf.default
  conf/nebula-storaged.conf.production
  src/kvstore/RocksEngine.cpp
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/test/RocksEngineTest.cpp
  src/utils/NebulaKeyUtils.h
Labels: ready-for-testing

#521 Revert "Improved data write logic to avoid reading dirty data"
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/test/MemoryLockTest.cpp
  src/utils/MemoryLockWrapper.h
Labels: ready-for-testing

#525 re-submit "Improved data write logic to avoid reading dirty data"
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/test/MemoryLockTest.cpp
  src/utils/MemoryLockWrapper.h
Labels: ready-for-testing

#520 [issue 1066]: enhance service script to return version information for '-v' option
  scripts/nebula.service
  scripts/utils.sh
Labels: ready-for-testing

#526 CreateBackup: backup IncrementalId as well
  src/meta/MetaServiceUtils.cpp
  src/meta/MetaServiceUtils.h
  src/meta/processors/BaseProcessor.inl
Labels: ready-for-testing

#528 fix task in recovered balance plan is still marked as FAILED
  src/meta/processors/admin/AdminClient.cpp
  src/meta/processors/admin/Balancer.cpp
  src/meta/processors/partsMan/ListHostsProcessor.cpp
  src/storage/StorageFlags.cpp
Labels: ready-for-testing

#533 Fix db_dump print int vid
  src/storage/mutate/AddEdgesAtomicProcessor.cpp
  src/storage/test/TossEnvironment.h
  src/storage/transaction/TransactionManager.cpp
  src/tools/db-dump/DbDumper.cpp
  src/tools/db-dump/DbDumper.h
Labels: ready-for-testing

#536 fix failed ut
  src/meta/test/MetaClientTest.cpp
Labels: ready-for-testing

#532 Replace vertex lru cache with rocksdb row cache
  src/kvstore/RocksEngineConfig.cpp
  src/kvstore/RocksEngineConfig.h
  src/kvstore/test/RocksEngineTest.cpp
  src/storage/GraphStorageServiceHandler.cpp
  src/storage/GraphStorageServiceHandler.h
  src/storage/StorageFlags.cpp
  src/storage/StorageFlags.h
  src/storage/exec/EdgeNode.h
  src/storage/exec/GetPropNode.h
  src/storage/exec/HashJoinNode.h
  src/storage/exec/IndexEdgeNode.h
  src/storage/exec/IndexVertexNode.h
  src/storage/exec/StorageIterator.h
  src/storage/exec/TagNode.h
  src/storage/index/LookupBaseProcessor.h
  src/storage/index/LookupBaseProcessor.inl
  src/storage/index/LookupProcessor.h
  src/storage/mutate/AddEdgesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.cpp
  src/storage/mutate/AddVerticesProcessor.h
  src/storage/mutate/DeleteEdgesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.cpp
  src/storage/mutate/DeleteVerticesProcessor.h
  src/storage/mutate/UpdateVertexProcessor.cpp
  src/storage/mutate/UpdateVertexProcessor.h
  src/storage/query/GetNeighborsProcessor.cpp
  src/storage/query/GetNeighborsProcessor.h
  src/storage/query/GetPropProcessor.cpp
  src/storage/query/GetPropProcessor.h
  src/storage/query/QueryBaseProcessor.h
  src/storage/test/CMakeLists.txt
  src/storage/test/GetNeighborsTest.cpp
  src/storage/test/IndexScanTest.cpp
  src/storage/test/QueryStatsTest.cpp
  src/storage/test/QueryTestUtils.h
  src/storage/test/UpdateEdgeTest.cpp
  src/storage/test/VertexCacheTest.cpp
  src/storage/transaction/TossEdgeIterator.h
Labels: ready-for-testing
